import SwiftUI

// HCC: root of the Training tab in cloud mode — the web app's Wendler 5/3/1
// tracker, ported.
//
// What the server owns and what this screen owns:
//   * the cycle, its week, its training maxes, every stored session and every
//     stored set come from `GET /api/training` and are never recomputed here;
//   * the resolved week (what a Tuesday IS) is a server answer too — it depends
//     on stored plan rows and on the last week actually trained, so the phone
//     renders `weekPlan`/`nextWeekPlan` and never guesses a third week;
//   * only the PREVIEW of a day that has not been started has no server rows to
//     draw, and that is generated by `HCCFiveThreeOne`, the 1:1 port of the
//     server's own `fiveThreeOne.ts`.
//
// Every write goes through `HealthDataStore`; this file never touches the
// network.

struct HCCTrainingView: View {
  @ObservedObject var store: HealthDataStore
  @ObservedObject var state: HCCTrainingState

  init(store: HealthDataStore) {
    self.store = store
    self.state = store.hccTraining
  }

  /// Whether the live workout screen exists in this build. It does —
  /// `HCCLiveSetupSheet` / `HCCLiveActivityView` — so the mockup's "Start live
  /// activity" button is drawn. Set this back to `false` and the button
  /// disappears rather than becoming a control that cannot do anything.
  static let liveActivityIsAvailable = true

  @State private var confirmingCycleStart: CycleStart?
  // HCC: the started session a "Cancel session" tap is asking about. Non-nil
  // presents the confirmation; nothing is deleted until it is answered.
  @State private var confirmingCancel: HCCTrainingSession?
  // HCC: a partial "Finish session" or an "Add workout" waiting on its answer.
  // One dialog for both, on a view of its own (the ScrollViewReader), so no two
  // confirmation modifiers share a view.
  @State private var sessionPrompt: SessionPrompt?
  // HCC: the conditioning title a live session was started for. Non-nil
  // presents the same setup sheet Home uses, pre-filled with that day's name so
  // the stored activity carries it.
  @State private var liveTitle: HCCTrainingLiveStart?

  var body: some View {
    HCCScreen {
      HCCReauthBanner(devices: store.hcc.devices)
      // The reader resolves against `HCCScreen`'s own ScrollView; its VStack
      // repeats the screen's spacing of 10, because this is now that stack's
      // single child. Same shape as cloud Home, and for the same reason: this
      // screen is several screens tall and `simctl` cannot scroll.
      ScrollViewReader { scroller in
        VStack(alignment: .leading, spacing: 10) {
          screenContent
        }
        .onAppear { scrollToDebugAnchorIfRequested(scroller) }
        // On the inner stack rather than beside the cycle dialog on the root, so
        // the two confirmation modifiers never share a view.
        .confirmationDialog(
          "Cancel this session?",
          isPresented: Binding(
            get: { confirmingCancel != nil },
            set: { if !$0 { confirmingCancel = nil } }
          ),
          titleVisibility: .visible
        ) {
          if let session = confirmingCancel {
            Button("Cancel session", role: .destructive) {
              confirmingCancel = nil
              Task { await store.cancelHCCTrainingSession(session) }
            }
            Button("Keep session", role: .cancel) { confirmingCancel = nil }
          }
        } message: {
          if let session = confirmingCancel { Text(Self.cancelMessage(session)) }
        }
      }
      .confirmationDialog(
        sessionPrompt?.question ?? "",
        isPresented: Binding(
          get: { sessionPrompt != nil },
          set: { if !$0 { sessionPrompt = nil } }
        ),
        titleVisibility: .visible
      ) {
        switch sessionPrompt {
        case let .finish(session, _)?:
          Button("Finish session") {
            sessionPrompt = nil
            Task { await store.patchHCCTrainingSession(session, status: .done) }
          }
          Button("Keep logging", role: .cancel) { sessionPrompt = nil }
        case let .addWorkout(date, _, titles)?:
          ForEach(titles, id: \.self) { title in
            Button(title) {
              sessionPrompt = nil
              addWorkout(date: date, title: title)
            }
          }
          Button("Cancel", role: .cancel) { sessionPrompt = nil }
        case let .remove(session, _)?:
          Button("Remove", role: .destructive) {
            sessionPrompt = nil
            // The DELETE route, with the same optimistic remove + rollback the
            // strength cancel uses; nothing about it is strength-specific.
            Task { await store.cancelHCCTrainingSession(session) }
          }
          Button("Keep it", role: .cancel) { sessionPrompt = nil }
        case nil:
          EmptyView()
        }
      } message: {
        if let detail = sessionPrompt?.detail { Text(detail) }
      }
    }
    .task {
      #if DEBUG
      // The ported program math, printed for the run that verifies it against
      // `src/lib/fiveThreeOne.ts`. Off unless HCC_DEBUG_531_CHECK=1.
      HCCFiveThreeOneSelfCheck.runIfRequested()
      #endif
      await store.loadHCCTrainingIfNeeded()
      applyDebugWeekIfRequested()
      #if DEBUG
      await runDebugActionIfRequested()
      #endif
    }
    .confirmationDialog(
      confirmingCycleStart?.question ?? "",
      isPresented: Binding(
        get: { confirmingCycleStart != nil },
        set: { if !$0 { confirmingCycleStart = nil } }
      ),
      titleVisibility: .visible
    ) {
      if let pending = confirmingCycleStart {
        Button(pending.confirmTitle, role: pending.isDestructive ? .destructive : nil) {
          let body = pending.body
          confirmingCycleStart = nil
          Task { await store.runHCCTrainingCycleAction(body) }
        }
        Button("Cancel", role: .cancel) { confirmingCycleStart = nil }
      }
    } message: {
      if let pending = confirmingCycleStart { Text(pending.detail) }
    }
    // HCC: the live workout, opened from a conditioning day.
    .sheet(item: $liveTitle) { start in
      HCCLiveSetupSheet(store: store, titleOverride: start.title)
    }
  }

  @ViewBuilder
  private var screenContent: some View {
    Group {
      HCCDetailHeader(title: "Training", subtitle: subtitle, showsBack: false)

      if let data = state.data, let cycle = data.cycle {
        content(data: data, cycle: cycle)
      } else if let data = state.data, data.cycle == nil {
        // The server refuses STRENGTH sessions without an active cycle, so
        // nothing here would succeed; say that rather than offering it.
        HCCEmptyNote(
          "No active 5/3/1 cycle. Start one on your Command Center and the wave, "
            + "the week strip and the progression appear here."
        )
        .hccCard()
      } else if let error = state.errorText {
        HCCErrorNote(error) { await store.reloadHCCTraining() }
      } else {
        HCCLoadingNote().hccCard()
      }

      if let failure = state.lastError {
        HCCErrorNote(failure, title: "Not saved")
      }
    }
  }

  private var subtitle: String {
    guard let cycle = state.data?.cycle else { return "Wendler 5/3/1" }
    return "Cycle \(cycle.number) · week \(cycle.week) · \(HCCFiveThreeOne.weekLabel(cycle.week))"
  }

  // ── Body ───────────────────────────────────────────────────────────────────

  @ViewBuilder
  private func content(data: HCCTrainingData, cycle: HCCTrainingCycle) -> some View {
    let weekStart = state.shownWeekStart ?? data.weekStartYmd
    let days = state.shownWeekPlan
    // The shown week may be ahead of where the cycle sits, so the wave is
    // projected that many weeks rather than repeating the current prescription.
    let projected = HCCFiveThreeOne.projectWave(
      anchorWeek: cycle.week,
      tms: cycle.tmsByLift,
      // A cycle nobody has trained yet has not spent its current week, so the
      // next calendar week is still that week — otherwise a mid-week reset of
      // the training maxes skips the new wave's 5s week. Same rule as the web.
      // "Trained" means logged work, not a row: since 2026-09-29 a cycle start
      // carries started-but-unlifted days onto the new cycle, and counting those
      // would preview next week one wave step early.
      weekOffset: HCCFiveThreeOne.programWeekOffset(
        state.weekOffset,
        cycleHasSessions: data.cycleSessions.contains { !$0.isStillAPlan }
      )
    )

    // The day being shown. Never trusted straight from state: a stored pick can
    // be a date in the other week (the strip toggles between two), so it only
    // counts when the shown week actually contains it. Today is the fallback
    // when today is in view; otherwise the first day of the week is.
    let selected =
      days.first { $0.date == state.selectedDate }
      ?? days.first { $0.date == data.todayYmd }
      ?? days.first

    HCCTrainingWeekCard(
      weekStart: weekStart,
      todayYmd: data.todayYmd,
      days: days,
      sessions: data.sessions,
      weekOffset: state.weekOffset,
      selectedDate: selected?.date,
      helper: helperText,
      onShift: { delta in
        let range = HCCTrainingState.weekOffsetRange
        let next = min(range.upperBound, max(range.lowerBound, state.weekOffset + delta))
        guard next != state.weekOffset else { return }
        // Keep the same weekday across the jump, except when landing back on the
        // real calendar week, where today is the more useful default. The web
        // strip's rule, so both clients move the selection the same way. Shift by
        // the delta, not by +7: the strip pages backwards now too.
        let carried = selected?.date ?? data.todayYmd
        state.weekOffset = next
        state.selectedDate =
          next == 0 ? data.todayYmd : HCCFiveThreeOne.addDays(carried, delta * 7)
      },
      onSelectDay: { date in state.selectedDate = date }
    )
    .id(HCCTrainingAnchor.week.rawValue)
    // A week outside the payload's two is fetched, never guessed. Keyed on the
    // week so paging re-runs it; the store no-ops a week already held or in
    // flight, so this cannot loop or double-fetch.
    .task(id: weekStart) {
      guard state.weekOffset != 0, state.weekOffset != 1 else { return }
      await store.loadHCCTrainingWeek(weekStart: weekStart)
    }

    // Always on screen, for whichever day is selected — it is how a day's
    // workout is changed, so it is not something to go hunting for behind a
    // second tap (Chris, 2026-09-08).
    if let day = selected {
      HCCTrainingPickerCard(
        dayKey: day.date,
        current: day,
        isEnabled: !state.isWriting,
        onPick: { choice in
          Task { await store.setHCCTrainingDayPlan(date: day.date, choice: choice) }
        }
      )
    }

    weekBody(
      data: data,
      cycle: cycle,
      days: days,
      week: projected.week,
      tms: projected.tms,
      selected: selected
    )

    // Progression belongs to the day being shown, not to the tab: on a squat +
    // bench day these are squat and bench, and on a conditioning or rest day
    // there is no lift to chart, so the block is not there at all.
    let progressionLifts = selected.map { Self.progressionLifts(day: $0, data: data) } ?? []

    ForEach(Array(progressionLifts.enumerated()), id: \.element) { offset, lift in
      HCCTrainingProgressionCard(
        lift: lift,
        trainingMaxKg: cycle.tm(lift) ?? 0,
        history: data.history(lift)
      )
      .modifier(HCCTrainingAnchorID(id: offset == 0 ? HCCTrainingAnchor.progression.rawValue : nil))
    }

    HCCTrainingButtons(specs: weekControls(cycle: cycle, data: data))
      .id(HCCTrainingAnchor.controls.rawValue)
  }

  /// The lifts whose progression belongs under the selected day: none unless it
  /// is a lifting day, and then exactly the lifts it runs, in the order it runs
  /// them — so a "Squat + Bench" day charts squat then bench, and nothing else.
  ///
  /// Logged work wins over the plan, the same rule the day's own cards use: when
  /// a strength session exists its sets name the lifts, so a day trained off-plan
  /// charts what was actually lifted rather than what was scheduled. `groupByLift`
  /// is reused for that because it already returns distinct lifts in the day's
  /// order.
  ///
  /// It replaced a fixed `[.squat, .bench, .deadlift, .press]` block that drew all
  /// four on every day, including conditioning and rest days (Chris, 2026-09-08).
  private static func progressionLifts(day: HCCResolvedDay, data: HCCTrainingData) -> [HCCLiftKey] {
    if let session = data.sessions(on: day.date).first(where: { $0.kind == .strength }) {
      let logged = groupByLift(session.sets, order: day.lifts).map(\.lift)
      if !logged.isEmpty { return logged }
    }
    // No session yet: the plan decides, and only a lifting day has lifts. Matches
    // `showsStrength` in dayCards, so the chart block and the day's card agree.
    return day.option == .strength ? day.lifts : []
  }

  private var helperText: String {
    if state.weekOffset == 0 { return "Tap a day to show it." }
    // Behind today the week is history — it is read from what was logged and
    // what was assigned, so "defaults copied from this week" would be a lie
    // about it (and was, for every backward offset, before paging existed).
    if state.weekOffset < 0 { return "Already happened. Tap a day to see or correct it." }
    if state.weekOffset > 1 { return "Ahead of next week. Tap a day to show it." }
    return state.nextWeekEdited
      ? "Edited. Other days still default to this week's pattern."
      : "Defaults copied from this week. Tap a day to show it."
  }

  // ── The shown week ─────────────────────────────────────────────────────────

  /// The selected day of the shown week, and only it.
  ///
  /// History, because this has moved twice. It first drew TODAY plus the next
  /// strength day still ahead — on a Sunday whose plan says rest that is a blank
  /// screen, with the week's logged sessions nowhere on the phone. So it went to
  /// every non-rest day of the week at once, which fixed the hiding but stacked
  /// several days' workouts under one tap (Chris, 2026-09-08: "it shows the
  /// workouts for multiple days"). Now it draws exactly the day the strip has
  /// selected, which is the web page's behaviour.
  ///
  /// The week is still not hidden: the strip above carries all seven days with
  /// their tags and their done marks, so any of them is one tap away. And a rest
  /// day is now reachable — it was filtered out entirely before, so a day the
  /// plan called rest could not be inspected or given a workout from here.
  @ViewBuilder
  private func weekBody(
    data: HCCTrainingData,
    cycle: HCCTrainingCycle,
    days: [HCCResolvedDay],
    week: Int,
    tms: [HCCLiftKey: Double],
    selected: HCCResolvedDay?
  ) -> some View {
    if state.weekOffset > 0 {
      HCCSectionHeader(title: state.weekOffset == 1 ? "Next week" : "Ahead")
      HCCFootnote(
        "Week \(week) — \(HCCFiveThreeOne.weekLabel(week)). Nothing here has been started; "
          + "the numbers come from that week's training maxes."
      )
    } else if state.weekOffset < 0 {
      HCCSectionHeader(title: "Earlier")
      HCCFootnote(
        "Week \(week) — \(HCCFiveThreeOne.weekLabel(week)). This week has already happened: "
          + "each day shows what was logged on it, or what it was assigned."
      )
    }

    if state.isShownWeekLoading {
      HCCLoadingNote().hccCard()
    } else if days.isEmpty {
      HCCEmptyNote("This week has not been resolved yet.").hccCard()
    } else if let day = selected {
      // The handoff's section marker above the day's cards is a micro-label
      // ("TODAY"), not a display-weight section title. Same string as before —
      // `HCCLabel` uppercases it.
      HCCLabel(Self.dayHeading(day: day, todayYmd: data.todayYmd))
        .padding(.top, 6)
        .padding(.leading, 2)
      dayCards(
        day: day,
        data: data,
        cycle: cycle,
        week: week,
        tms: tms,
        label: Self.dayLabel(day: day, todayYmd: data.todayYmd),
        // Only a day that has not arrived is a preview. Today and the days
        // behind it happened, so they start, log and mark like today always
        // did. Day keys are 'YYYY-MM-DD', where string order IS date order.
        isPreview: day.date > data.todayYmd
      )
      addWorkoutControl(day: day, data: data)
    }
  }

  /// "Add workout" — a second (or third) conditioning session on a day that has
  /// arrived, logged as done. 2026-10-03: a day used to be ONE thing, so a
  /// CrossFit class on a lifting day could not be recorded without throwing the
  /// lift away through the plan picker, whose PUT rewrites the day. This POSTs a
  /// session and leaves the plan alone; the server allows any number of sessions
  /// per day and is idempotent on (date, title), so the titles already on the
  /// day are not offered again. Days ahead get no button — nothing has happened
  /// on them to log.
  @ViewBuilder
  private func addWorkoutControl(day: HCCResolvedDay, data: HCCTrainingData) -> some View {
    let titles = Self.addableWorkoutTitles(day: day, daySessions: data.sessions(on: day.date))
    if day.date <= data.todayYmd, !titles.isEmpty {
      HCCButtonRow(
        secondary: HCCButtonSpec(title: "Add workout", isEnabled: !state.isWriting, systemImage: "plus") {
          sessionPrompt = .addWorkout(
            date: day.date,
            heading: Self.promptDayName(day.date, todayYmd: data.todayYmd),
            titles: titles
          )
        }
      )
    }
  }

  /// The conditioning workouts the catalog knows, minus the ones the day already
  /// holds and minus the plan's own (its card is already on screen with its own
  /// "Mark done"). Catalog titles only, because those are the ones the strip and
  /// the cards know how to name.
  static func addableWorkoutTitles(day: HCCResolvedDay, daySessions: [HCCTrainingSession]) -> [String] {
    var taken = Set(daySessions.filter { $0.kind == .conditioning }.map(\.title))
    if day.option == .conditioning { taken.insert(day.title) }
    return HCCFiveThreeOne.dayOptionCatalog()
      .filter { $0.option == .conditioning && !taken.contains($0.title) }
      .map(\.title)
  }

  private func addWorkout(date: String, title: String) {
    Task {
      await store.startHCCTrainingSession(
        HCCTrainingSessionCreate(
          date: date,
          kind: HCCTrainingSessionKind.conditioning.rawValue,
          title: title,
          status: HCCTrainingSessionStatus.done.rawValue
        )
      )
    }
  }

  private static func dayHeading(day: HCCResolvedDay, todayYmd: String) -> String {
    guard day.date != todayYmd else { return "Today" }
    return "\(HCCTrainingFormat.shortDow(day.date)) \(HCCTrainingFormat.dayNumber(day.date))"
  }

  /// The pill each card carries: where this day sits relative to now. Never a
  /// claim about what happened on it — the card's own rows say that.
  private static func dayLabel(day: HCCResolvedDay, todayYmd: String) -> String {
    if day.date == todayYmd { return "Today" }
    return day.date < todayYmd ? "Earlier" : "Preview"
  }

  /// A day, drawn as one card per lift for a strength day and one card per
  /// conditioning workout — the plan's, and every one logged on the day.
  @ViewBuilder
  private func dayCards(
    day: HCCResolvedDay,
    data: HCCTrainingData,
    cycle: HCCTrainingCycle,
    week: Int,
    tms: [HCCLiftKey: Double],
    label: String,
    isPreview: Bool
  ) -> some View {
    let daySessions = data.sessions(on: day.date)
    let strength = daySessions.first { $0.kind == .strength }
    // Logged work wins over the plan: a strength session on a conditioning day
    // still shows its lifts, and the other way round. REVISED 2026-10-03: every
    // conditioning session on the day gets its card, not just the first, since
    // "Add workout" puts a second one on a day.
    let conditioning = Self.conditioningEntries(day: day, daySessions: daySessions)
    let showsStrength = strength != nil || day.option == .strength
    let showsConditioning = !conditioning.isEmpty

    if showsStrength {
      if let session = strength {
        startedStrength(session: session, day: day, cycle: cycle, label: label)
      } else {
        previewStrength(day: day, week: week, tms: tms, label: label, isPast: day.date < data.todayYmd)
      }
    }

    ForEach(conditioning) { entry in
      HCCTrainingConditioningCard(
        title: entry.title,
        subtitle: entry.subtitle,
        pillText: label,
        isPreview: isPreview,
        isDone: entry.session?.status == .done,
        isOptional: entry.isOptional,
        isEnabled: !state.isWriting,
        onMark: { markConditioning(date: day.date, title: entry.title, session: entry.session) },
        // HCC: the same setup sheet Home opens, named after this workout.
        onStartLive: Self.liveActivityIsAvailable
          ? { liveTitle = HCCTrainingLiveStart(title: entry.title) }
          : nil,
        onRemove: entry.isAdded
          ? entry.session.map { session in
            { sessionPrompt = .remove(session: session, day: Self.promptDayName(day.date, todayYmd: data.todayYmd)) }
          }
          : nil
      )
      if let session = entry.session {
        noteCard(session: session)
      }
    }

    if !showsStrength && !showsConditioning {
      // A day the server resolved as REST_DEFAULT holds no record at all — no
      // session, no pick. Calling that "rest day" asserts a decision he never
      // made, which is the exact claim the server stopped making on 2026-09-14;
      // repeating it here would put it straight back on screen.
      HCCEmptyNote(
        day.source == .restDefault
          ? "\(label): nothing logged. Use the picker above to say what this day was."
          : "\(label): rest day."
      )
      .hccCard()
    }
  }

  /// One conditioning card's worth: a logged session, or the plan's workout
  /// that has not been logged yet.
  struct ConditioningEntry: Identifiable {
    let id: String
    let title: String
    let subtitle: String
    let isOptional: Bool
    let session: HCCTrainingSession?
    /// Logged on top of the day rather than being the day's own workout.
    var isAdded = false
  }

  /// The plan's own workout first — logged or not — then every other
  /// conditioning session on the day, in the payload's order, marked as added.
  ///
  /// The day's own session is the one titled as the day OR as one of its
  /// weekday template's alternatives — a Tuesday offering Norwegian 4×4 /
  /// CrossFit and logged as CrossFit is still Tuesday's workout, not an added
  /// one. The web's `isAlternative` rule, and strict on purpose: a class added
  /// to a Bouldering day must not stand in for the Bouldering. Before
  /// 2026-10-03 the first session replaced the plan card whatever it was
  /// called, which made a second workout on a planned day hide the planned one.
  static func conditioningEntries(day: HCCResolvedDay, daySessions: [HCCTrainingSession]) -> [ConditioningEntry] {
    let logged = daySessions.filter { $0.kind == .conditioning }
    let alternatives = templateAlternatives(day.date)
    let catalog = HCCFiveThreeOne.dayOptionCatalog()
    func subtitle(_ title: String) -> String {
      alternatives.first { $0.title == title }?.subtitle
        ?? (title == day.title ? day.subtitle : nil)
        ?? catalog.first { $0.option == .conditioning && $0.title == title }?.subtitle
        ?? "Conditioning"
    }
    var entries: [ConditioningEntry] = []
    if day.option == .conditioning {
      let own = logged.first { session in
        session.title == day.title || alternatives.contains { $0.title == session.title }
      }
      let title = own?.title ?? day.title
      entries.append(
        ConditioningEntry(
          id: own?.id ?? "plan:\(day.date)",
          title: title,
          subtitle: subtitle(title),
          isOptional: day.optional,
          session: own
        )
      )
    }
    for session in logged where !entries.contains(where: { $0.session?.id == session.id }) {
      entries.append(
        ConditioningEntry(
          id: session.id,
          title: session.title,
          subtitle: subtitle(session.title),
          isOptional: false,
          session: session,
          isAdded: true
        )
      )
    }
    return entries
  }

  /// The weekday template's "which one?" alternatives for a day key — empty for
  /// a weekday whose template offers none.
  private static func templateAlternatives(_ dayKey: String) -> [HCCDayOption] {
    let dow = HCCFiveThreeOne.dow(dayKey)
    return HCCFiveThreeOne.weekTemplate.first { $0.dow == dow }?.options ?? []
  }

  /// How a prompt names a day mid-sentence: "today", else "Fri 2".
  static func promptDayName(_ dayKey: String, todayYmd: String) -> String {
    dayKey == todayYmd
      ? "today"
      : "\(HCCTrainingFormat.shortDow(dayKey)) \(HCCTrainingFormat.dayNumber(dayKey))"
  }

  /// A strength day that has been started: the server's own stored sets, each
  /// tickable, and the AMRAP bar on the set that measures.
  @ViewBuilder
  private func startedStrength(
    session: HCCTrainingSession,
    day: HCCResolvedDay,
    cycle: HCCTrainingCycle,
    label: String
  ) -> some View {
    // The session records the week it was prescribed for; that is the week its
    // stored weights belong to, whatever the cycle has since moved to.
    let week = HCCFiveThreeOne.clampWeek(session.week ?? cycle.week)
    ForEach(Self.groupByLift(session.sets, order: day.lifts), id: \.lift) { group in
      HCCTrainingLiftCard(
        lift: group.lift,
        // The maxes this session was generated from, not the active cycle's —
        // paging back to a finished wave must not re-label its sets.
        trainingMaxKg: session.ownTm(group.lift) ?? cycle.tm(group.lift) ?? 0,
        week: week,
        pillText: label,
        isPreview: false,
        rows: group.sets.map {
          HCCTrainingSetTable.Row(id: $0.id, prescribed: $0.prescribed, actualReps: $0.actualReps, set: $0)
        },
        isEnabled: !state.isWriting,
        onToggle: { row in
          guard let set = row.set else { return }
          Task {
            await store.logHCCTrainingSet(
              sessionId: session.id,
              set: set,
              actualReps: set.actualReps == nil ? set.targetReps : nil
            )
          }
        },
        sessionIsFinished: session.status == .done,
        footer: { amrapFooter(session: session, sets: group.sets) }
      )
    }
    noteCard(session: session)
    // Only while the day is still in progress: a finished session is history,
    // and "cancel" is the wrong word for removing one.
    if session.status != .done {
      let logged = session.sets.filter { $0.actualReps != nil }.count
      HCCButtonRow(
        // 2026-10-03: Finish is how a half-logged session ends. Before it, the
        // only ways out were logging every set (the server marks the session
        // DONE on the last one) or Cancel, which deletes the sets that WERE
        // logged. Withheld while nothing is logged — finishing an empty session
        // records a workout that did not happen; Cancel is the exit for that.
        primary: logged > 0
          ? HCCButtonSpec(title: "Finish session", isEnabled: !state.isWriting, systemImage: "checkmark") {
            finish(session: session, order: day.lifts)
          }
          : nil,
        secondary: HCCButtonSpec(title: "Cancel session", isEnabled: !state.isWriting, isDestructive: true) {
          confirmingCancel = session
        }
      )
    } else {
      // The web's "Reopen": back to PLANNED, sets untouched. A finish is a
      // status, not a deletion, so it is always undoable.
      HCCButtonRow(
        secondary: HCCButtonSpec(title: "Reopen", isEnabled: !state.isWriting) {
          Task { await store.patchHCCTrainingSession(session, status: .planned) }
        }
      )
    }
  }

  /// Every set logged: finish at once. Some missing: ask first, naming what
  /// will be recorded as not done. The PATCH does no set-completeness check, so
  /// this question is the only place the shortfall is said out loud.
  private func finish(session: HCCTrainingSession, order: [HCCLiftKey]) {
    let logged = session.sets.filter { $0.actualReps != nil }.count
    guard logged > 0 else { return }
    if logged == session.sets.count {
      Task { await store.patchHCCTrainingSession(session, status: .done) }
    } else {
      sessionPrompt = .finish(session: session, order: order)
    }
  }

  /// "Military press not done. The 4 unlogged sets stay on record as not done…"
  static func finishMessage(_ session: HCCTrainingSession, order: [HCCLiftKey]) -> String {
    let unlogged = session.sets.filter { $0.actualReps == nil }.count
    let missing = groupByLift(session.sets, order: order)
      .filter { group in group.sets.allSatisfy { $0.actualReps == nil } }
      .map(\.lift.label)
    var parts: [String] = []
    if !missing.isEmpty { parts.append("\(Self.listJoined(missing)) not done.") }
    parts.append(
      "The \(unlogged) unlogged set\(unlogged == 1 ? "" : "s") stay\(unlogged == 1 ? "s" : "") on record as not done; "
        + "Reopen brings the session back."
    )
    return parts.joined(separator: " ")
  }

  /// "A", "A and B", "A, B and C".
  private static func listJoined(_ items: [String]) -> String {
    guard items.count > 1, let last = items.last else { return items.first ?? "" }
    return items.dropLast().joined(separator: ", ") + " and " + last
  }

  /// What the confirmation says will go. Logged sets are named because they are
  /// the one part a fresh Start cannot regenerate; the day's pick staying is
  /// named because it is what makes the cancel useful.
  static func cancelMessage(_ session: HCCTrainingSession) -> String {
    let logged = session.sets.filter { $0.actualReps != nil }.count
    let lost = logged == 0
      ? "Nothing has been logged in it yet."
      : "\(logged) logged set\(logged == 1 ? "" : "s") will be deleted."
    return "\(session.title) is removed. \(lost) The day keeps its workout, so it goes back to a preview; "
      + "start it again for sets from the current cycle and week."
  }

  @ViewBuilder
  private func amrapFooter(session: HCCTrainingSession, sets: [HCCTrainingSet]) -> some View {
    if let amrap = sets.first(where: \.isAmrap) {
      HCCTrainingAmrapBar(
        weightKg: amrap.targetWeightKg,
        reps: state.amrapDraft(for: amrap),
        loggedReps: amrap.actualReps,
        isEnabled: !state.isWriting,
        onStep: { delta in
          state.amrapDrafts[amrap.id] = max(0, min(100, state.amrapDraft(for: amrap) + delta))
        },
        onLog: {
          let reps = state.amrapDraft(for: amrap)
          Task { await store.logHCCTrainingSet(sessionId: session.id, set: amrap, actualReps: reps) }
        }
      )
    }
  }

  /// A strength day with nothing stored yet: the prescription generated from the
  /// training maxes, and the button that turns it into a session the server owns.
  ///
  /// That button is offered on EVERY day, which is what the web page has always
  /// done. It was briefly withheld from a day that had not arrived, on the
  /// reasoning that a card saying Preview should not also say Start — a claim
  /// about the label, not about the day. It left the phone unable to open
  /// tomorrow's workout at all (Chris, 2026-09-14: "stuck in preview mode with
  /// no way to start the activity"), while the same day on the web started with
  /// one click. Preview describes where the numbers come from — generated from
  /// the training maxes rather than read from stored sets — and stays on the
  /// pill; it was never a reason to remove the control.
  @ViewBuilder
  private func previewStrength(
    day: HCCResolvedDay,
    week: Int,
    tms: [HCCLiftKey: Double],
    label: String,
    /// A day already behind today opens as a LOG of what was done, not a start,
    /// and its weights are a reconstruction from today's maxes — so both the
    /// button and the footnote say so instead of implying otherwise.
    isPast: Bool
  ) -> some View {
    ForEach(day.lifts, id: \.self) { lift in
      let tm = tms[lift] ?? 0
      HCCTrainingLiftCard(
        lift: lift,
        trainingMaxKg: tm,
        week: week,
        pillText: label,
        isPreview: true,
        rows: HCCFiveThreeOne.waveSets(tmKg: tm, week: week).map {
          HCCTrainingSetTable.Row(id: "\(day.date):\(lift.rawValue):\($0.setIndex)", prescribed: $0)
        }
      )
    }
    if !day.lifts.isEmpty {
      HCCButtonRow(
        primary: HCCButtonSpec(
          title: isPast ? "Log this session" : "Start session",
          isEnabled: !state.isWriting
        ) {
          Task {
            await store.startHCCTrainingSession(
              HCCTrainingSessionCreate(
                date: day.date,
                kind: HCCTrainingSessionKind.strength.rawValue,
                lifts: day.lifts.map(\.rawValue),
                week: week
              )
            )
          }
        }
      )
      HCCFootnote(
        isPast
          ? "Reconstructed from week \(week)'s training maxes — correct the reps as you log them."
          : "Sets are generated from week \(week)'s training maxes."
      )
    }
  }

  private func noteCard(session: HCCTrainingSession) -> some View {
    HCCTrainingNoteField(
      placeholder: "How it felt, bar speed, anything to remember",
      text: Binding(
        get: { state.noteDraft(for: session) },
        set: { state.noteDrafts[session.id] = $0 }
      ),
      isEnabled: !state.isWriting,
      onCommit: {
        let draft = state.noteDraft(for: session).trimmingCharacters(in: .whitespacesAndNewlines)
        guard draft != (session.notes ?? "") else { return }
        Task { await store.patchHCCTrainingSession(session, notes: .some(draft.isEmpty ? nil : draft)) }
      }
    )
    .hccCard()
  }

  private func markConditioning(date: String, title: String, session: HCCTrainingSession?) {
    Task {
      if let session {
        await store.patchHCCTrainingSession(session, status: session.status == .done ? .planned : .done)
      } else {
        await store.startHCCTrainingSession(
          HCCTrainingSessionCreate(
            date: date,
            kind: HCCTrainingSessionKind.conditioning.rawValue,
            title: title,
            status: HCCTrainingSessionStatus.done.rawValue
          )
        )
      }
    }
  }

  /// The two questions `sessionPrompt` can ask.
  private enum SessionPrompt {
    /// A partial finish. `order` is the day's lift order, for naming the lifts
    /// with nothing logged in the order they run.
    case finish(session: HCCTrainingSession, order: [HCCLiftKey])
    case addWorkout(date: String, heading: String, titles: [String])
    /// Taking an ADDED conditioning workout off a day. `day` is the prompt's
    /// name for that day ("today", "Fri 2").
    case remove(session: HCCTrainingSession, day: String)

    var question: String {
      switch self {
      case let .finish(session, _):
        let logged = session.sets.filter { $0.actualReps != nil }.count
        return "Finish with \(logged) of \(session.sets.count) sets logged?"
      case let .addWorkout(_, heading, _):
        return "Add a workout to \(heading)"
      case let .remove(session, day):
        return "Remove \(session.title) from \(day)?"
      }
    }

    var detail: String {
      switch self {
      case let .finish(session, order):
        return HCCTrainingView.finishMessage(session, order: order)
      case .addWorkout:
        return "Logged as done on that day, next to what is already there. The day's plan does not change."
      case let .remove(session, _):
        let note = (session.notes ?? "").isEmpty ? "" : ", along with its note"
        return "\(session.title) comes off the day\(note). The rest of the day stays as it is."
      }
    }
  }

  // ── Next week ──────────────────────────────────────────────────────────────

  /// The next week is a preview, not a log: one line per day with the top set of
  /// each lift, which is the number that tells the owner how heavy the week is.
  // ── Wave controls ──────────────────────────────────────────────────────────

  /// Exactly the controls the web page offers in each state, and no others.
  /// Every step is reversible: advancing is a single tap, and without a way back
  /// a mis-tap strands the cycle a week ahead of real life.
  private func weekControls(cycle: HCCTrainingCycle, data: HCCTrainingData) -> [HCCButtonSpec] {
    var specs: [HCCButtonSpec] = []
    let busy = state.isWriting

    if cycle.week > 1 {
      specs.append(
        HCCButtonSpec(title: "Back to week \(cycle.week - 1)", isEnabled: !busy) {
          Task {
            await store.runHCCTrainingCycleAction(
              HCCTrainingCycleBody(action: "setWeek", week: cycle.week - 1)
            )
          }
        }
      )
    }

    // Offered only for a freshly-started cycle with no logged work: the server
    // refuses to delete a cycle that holds any, so this is never shown when it
    // could not succeed. REVISED 2026-09-29: a cycle start now carries days that
    // were started but not lifted onto the new cycle, and the revert hands them
    // back — so an unlogged session no longer counts; `isEmpty` would have hidden
    // the button after every such start.
    if cycle.number > 1 && cycle.week == 1 && data.cycleSessions.allSatisfy(\.isStillAPlan) {
      specs.append(
        HCCButtonSpec(title: "Back to cycle \(cycle.number - 1) deload", isEnabled: !busy) {
          confirmingCycleStart = .revert(number: cycle.number)
        }
      )
    }

    if cycle.week < 4 {
      specs.append(
        HCCButtonSpec(title: "Advance to week \(cycle.week + 1)", isEnabled: !busy) {
          Task { await store.runHCCTrainingCycleAction(HCCTrainingCycleBody(action: "advanceWeek")) }
        }
      )
    }

    if cycle.week == 4 || cycle.week == 3 {
      let skipping = cycle.week != 4
      specs.append(
        HCCButtonSpec(
          title: skipping ? "Skip deload · start cycle \(cycle.number + 1)" : "Start cycle \(cycle.number + 1)",
          isEnabled: !busy
        ) {
          confirmingCycleStart = .startNext(number: cycle.number, skippingDeload: skipping, tms: cycle.tmsByLift)
        }
      )
    }

    return specs
  }

  /// The two irreversible-feeling wave moves, and what each one will do to the
  /// training maxes — spelled out before it happens, the way the web page's
  /// confirm does.
  private enum CycleStart: Identifiable {
    case startNext(number: Int, skippingDeload: Bool, tms: [HCCLiftKey: Double])
    case revert(number: Int)

    var id: String {
      switch self {
      case let .startNext(number, skipping, _): "startNext/\(number)/\(skipping)"
      case let .revert(number): "revert/\(number)"
      }
    }

    var question: String {
      switch self {
      case let .startNext(number, skipping, _):
        skipping ? "Skip the deload and start cycle \(number + 1)?" : "Start cycle \(number + 1)?"
      case let .revert(number):
        "Undo starting cycle \(number)?"
      }
    }

    var detail: String {
      switch self {
      case let .startNext(_, _, tms):
        let lines = [HCCLiftKey.squat, .bench, .deadlift, .press].compactMap { lift -> String? in
          guard let current = tms[lift] else { return nil }
          return "\(lift.label): \(HCCFiveThreeOne.formatKg(current)) → "
            + "\(HCCFiveThreeOne.formatKg(HCCFiveThreeOne.nextTm(lift, currentKg: current))) kg"
        }
        return "Training maxes become:\n" + lines.joined(separator: "\n")
      case let .revert(number):
        return "Cycle \(number) is deleted and cycle \(number - 1) reopens at its deload week."
      }
    }

    var confirmTitle: String {
      switch self {
      case .startNext: "Start"
      case .revert: "Go back"
      }
    }

    var isDestructive: Bool {
      if case .revert = self { return true }
      return false
    }

    var body: HCCTrainingCycleBody {
      switch self {
      case .startNext: HCCTrainingCycleBody(action: "startNext")
      case .revert: HCCTrainingCycleBody(action: "revertCycleStart")
      }
    }
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  /// Sets arrive ordered by lift NAME, so a "Squat + Bench" day would otherwise
  /// render bench first. The day's resolved lift order is the record of the
  /// order the workout is actually run in.
  private static func groupByLift(
    _ sets: [HCCTrainingSet],
    order: [HCCLiftKey]
  ) -> [(lift: HCCLiftKey, sets: [HCCTrainingSet])] {
    var groups: [(lift: HCCLiftKey, sets: [HCCTrainingSet])] = []
    for set in sets {
      if let index = groups.firstIndex(where: { $0.lift == set.lift }) {
        groups[index].sets.append(set)
      } else {
        groups.append((set.lift, [set]))
      }
    }
    for index in groups.indices {
      groups[index].sets.sort { $0.setIndex < $1.setIndex }
    }
    if !order.isEmpty {
      func rank(_ lift: HCCLiftKey) -> Int { order.firstIndex(of: lift) ?? order.count }
      groups.sort { rank($0.lift) < rank($1.lift) }
    }
    return groups
  }

  /// `HCC_DEBUG_TRAINING_WEEK` — which calendar week the strip opens on, since
  /// `simctl` cannot tap the chip. `next` / `last`, or a signed offset
  /// (`-3`, `2`), clamped to `weekOffsetRange`. A backward offset is fetched
  /// like any other, so the screenshot shows the real resolved week.
  private func applyDebugWeekIfRequested() {
    #if DEBUG
    switch ProcessInfo.processInfo.environment["HCC_DEBUG_TRAINING_WEEK"] {
    case "next": state.weekOffset = 1
    case "last": state.weekOffset = -1
    case let raw?:
      if let n = Int(raw) {
        let range = HCCTrainingState.weekOffsetRange
        state.weekOffset = min(range.upperBound, max(range.lowerBound, n))
      }
    case nil: break
    }
    if let day = ProcessInfo.processInfo.environment["HCC_DEBUG_TRAINING_PICKER"], !day.isEmpty {
      state.selectedDate = day
    }
    #endif
  }

  #if DEBUG
  /// Runs ONE write from a launch environment variable, the way the Alarm and
  /// Customize sheets' `HCC_DEBUG_SAVE` does: `simctl` cannot tap, and a write
  /// path that has never been run is not a proved write path.
  ///
  /// It calls the same store methods the buttons call — no shortcut around the
  /// optimistic/reconcile/rollback shape — so what it proves is what a tap does.
  /// It MUTATES SERVER STATE: never set it against an instance whose data you
  /// are not willing to change.
  ///
  ///   `start`                 start today's strength session
  ///   `logset`                tick the first un-logged set of today's session
  ///   `amrap:<n>`             log n reps on today's first AMRAP set
  ///   `plan:<ymd>:<key>`      set that day to that `dayOptionCatalog` key
  ///   `note:<text>`           save a note on today's session
  ///   `finish` / `reopen`     PATCH today's strength session DONE / PLANNED,
  ///                           skipping the partial-finish question
  ///   `add:<ymd>:<title>`     add a DONE conditioning workout to that day
  private func runDebugActionIfRequested() async {
    guard let raw = ProcessInfo.processInfo.environment["HCC_DEBUG_TRAINING_SAVE"], !raw.isEmpty,
          let data = state.data
    else { return }
    let parts = raw.split(separator: ":", maxSplits: 2).map(String.init)
    let today = data.sessions(on: data.todayYmd)
    let strength = today.first { $0.kind == .strength }

    switch parts.first {
    case "start":
      guard let day = data.weekPlan.first(where: { $0.date == data.todayYmd }), !day.lifts.isEmpty else { return }
      let week = HCCFiveThreeOne.projectWave(
        anchorWeek: data.cycle?.week ?? 1, tms: [:], weekOffset: 0
      ).week
      await store.startHCCTrainingSession(
        HCCTrainingSessionCreate(
          date: day.date,
          kind: HCCTrainingSessionKind.strength.rawValue,
          lifts: day.lifts.map(\.rawValue),
          week: week
        )
      )
    case "logset":
      guard let session = strength,
            let set = session.sets.first(where: { !$0.isAmrap && $0.actualReps == nil })
      else { return }
      await store.logHCCTrainingSet(sessionId: session.id, set: set, actualReps: set.targetReps)
    case "amrap":
      guard let session = strength, let set = session.sets.first(where: \.isAmrap),
            let reps = Int(parts.count > 1 ? parts[1] : "")
      else { return }
      await store.logHCCTrainingSet(sessionId: session.id, set: set, actualReps: reps)
    case "plan":
      guard parts.count == 3,
            let choice = HCCFiveThreeOne.dayOptionCatalog().first(where: { $0.key == parts[2] })
      else { return }
      await store.setHCCTrainingDayPlan(date: parts[1], choice: choice)
    case "note":
      guard let session = strength, parts.count > 1 else { return }
      await store.patchHCCTrainingSession(session, notes: .some(parts[1]))
    case "finish", "reopen":
      guard let session = strength else { return }
      await store.patchHCCTrainingSession(session, status: parts[0] == "finish" ? .done : .planned)
    case "add":
      guard parts.count == 3 else { return }
      await store.startHCCTrainingSession(
        HCCTrainingSessionCreate(
          date: parts[1],
          kind: HCCTrainingSessionKind.conditioning.rawValue,
          title: parts[2],
          status: HCCTrainingSessionStatus.done.rawValue
        )
      )
    case "cycle":
      // `advanceWeek` / `setWeek:<n>` / `startNext` / `revertCycleStart` — the
      // wave controls, whose taps go through a confirmation the launch cannot
      // answer. This runs the same store call the confirmed button runs.
      guard parts.count > 1 else { return }
      await store.runHCCTrainingCycleAction(
        HCCTrainingCycleBody(action: parts[1], week: parts.count > 2 ? Int(parts[2]) : nil)
      )
    default:
      return
    }
    print("[hcc-training-debug] ran \(raw); lastError=\(state.lastError ?? "none")")
  }
  #endif
}

// ── Debug scroll anchors ─────────────────────────────────────────────────────

/// The scroll targets `HCC_DEBUG_TRAINING_ANCHOR` can name.
///
/// The Training tab is several screens tall and `simctl` cannot scroll; this is
/// the same trick `HCC_DEBUG_HOME_ANCHOR` uses for cloud Home, so each block can
/// be screenshotted from a launch with no UI automation. DEBUG only.
enum HCCTrainingAnchor: String, CaseIterable {
  case week
  case progression
  case controls
}

/// `.id` only when there is one to apply, so the non-anchored cards keep
/// SwiftUI's own identity rather than being handed a nil-ish constant.
private struct HCCTrainingAnchorID: ViewModifier {
  let id: String?

  func body(content: Content) -> some View {
    if let id {
      content.id(id)
    } else {
      content
    }
  }
}

extension HCCTrainingView {
  func scrollToDebugAnchorIfRequested(_ scroller: ScrollViewProxy) {
    #if DEBUG
    guard let raw = ProcessInfo.processInfo.environment["HCC_DEBUG_TRAINING_ANCHOR"],
          let anchor = HCCTrainingAnchor(rawValue: raw)
    else {
      return
    }
    // After the read lands, so the block being aimed at has its height. Several
    // times, because a debug write re-reads the payload and relays out after the
    // first jump, and a permission alert from another surface can land on top of
    // the second one.
    Task { @MainActor in
      for delay in [2, 4, 8] {
        try? await Task.sleep(for: .seconds(delay))
        scroller.scrollTo(anchor.rawValue, anchor: .top)
      }
    }
    #endif
  }
}
