import SwiftUI

// HCC: root of the Training tab in cloud mode — the web app's Wendler 5/3/1
// tracker, ported.
//
// What the server owns and what this screen owns:
//   * the cycle, its week, its training maxes, every stored session and every
//     stored set come from `GET /api/training` and are never recomputed here;
//   * the resolved week (what a Tuesday IS) is a server answer too — it depends
//     on stored plan rows and on the last week actually trained, so the phone
//     renders `weekPlan`/`nextWeekPlan` and never guesses a third week;
//   * only the PREVIEW of a day that has not been started has no server rows to
//     draw, and that is generated by `HCCFiveThreeOne`, the 1:1 port of the
//     server's own `fiveThreeOne.ts`.
//
// Every write goes through `HealthDataStore`; this file never touches the
// network.

struct HCCTrainingView: View {
  @ObservedObject var store: HealthDataStore
  @ObservedObject var state: HCCTrainingState

  init(store: HealthDataStore) {
    self.store = store
    self.state = store.hccTraining
  }

  /// Whether the live workout screen exists in this build. It does —
  /// `HCCLiveSetupSheet` / `HCCLiveActivityView` — so the mockup's "Start live
  /// activity" button is drawn. Set this back to `false` and the button
  /// disappears rather than becoming a control that cannot do anything.
  static let liveActivityIsAvailable = true

  @State private var confirmingCycleStart: CycleStart?
  // HCC: the conditioning title a live session was started for. Non-nil
  // presents the same setup sheet Home uses, pre-filled with that day's name so
  // the stored activity carries it.
  @State private var liveTitle: HCCTrainingLiveStart?

  var body: some View {
    HCCScreen {
      // The reader resolves against `HCCScreen`'s own ScrollView; its VStack
      // repeats the screen's spacing of 10, because this is now that stack's
      // single child. Same shape as cloud Home, and for the same reason: this
      // screen is several screens tall and `simctl` cannot scroll.
      ScrollViewReader { scroller in
        VStack(alignment: .leading, spacing: 10) {
          screenContent
        }
        .onAppear { scrollToDebugAnchorIfRequested(scroller) }
      }
    }
    .task {
      #if DEBUG
      // The ported program math, printed for the run that verifies it against
      // `src/lib/fiveThreeOne.ts`. Off unless HCC_DEBUG_531_CHECK=1.
      HCCFiveThreeOneSelfCheck.runIfRequested()
      #endif
      await store.loadHCCTrainingIfNeeded()
      applyDebugWeekIfRequested()
      #if DEBUG
      await runDebugActionIfRequested()
      #endif
    }
    .confirmationDialog(
      confirmingCycleStart?.question ?? "",
      isPresented: Binding(
        get: { confirmingCycleStart != nil },
        set: { if !$0 { confirmingCycleStart = nil } }
      ),
      titleVisibility: .visible
    ) {
      if let pending = confirmingCycleStart {
        Button(pending.confirmTitle, role: pending.isDestructive ? .destructive : nil) {
          let body = pending.body
          confirmingCycleStart = nil
          Task { await store.runHCCTrainingCycleAction(body) }
        }
        Button("Cancel", role: .cancel) { confirmingCycleStart = nil }
      }
    } message: {
      if let pending = confirmingCycleStart { Text(pending.detail) }
    }
    // HCC: the live workout, opened from a conditioning day.
    .sheet(item: $liveTitle) { start in
      HCCLiveSetupSheet(store: store, titleOverride: start.title)
    }
  }

  @ViewBuilder
  private var screenContent: some View {
    Group {
      HCCDetailHeader(title: "Training", subtitle: subtitle, showsBack: false)

      if let data = state.data, let cycle = data.cycle {
        content(data: data, cycle: cycle)
      } else if let data = state.data, data.cycle == nil {
        // The server refuses STRENGTH sessions without an active cycle, so
        // nothing here would succeed; say that rather than offering it.
        HCCEmptyNote(
          "No active 5/3/1 cycle. Start one on your Command Center and the wave, "
            + "the week strip and the progression appear here."
        )
        .hccCard()
      } else if let error = state.errorText {
        HCCErrorNote(error) { await store.reloadHCCTraining() }
      } else {
        HCCLoadingNote().hccCard()
      }

      if let failure = state.lastError {
        HCCErrorNote(failure, title: "Not saved")
      }
    }
  }

  private var subtitle: String {
    guard let cycle = state.data?.cycle else { return "Wendler 5/3/1" }
    return "Cycle \(cycle.number) · week \(cycle.week) · \(HCCFiveThreeOne.weekLabel(cycle.week))"
  }

  // ── Body ───────────────────────────────────────────────────────────────────

  @ViewBuilder
  private func content(data: HCCTrainingData, cycle: HCCTrainingCycle) -> some View {
    let weekStart = state.shownWeekStart ?? data.weekStartYmd
    let days = state.shownWeekPlan
    // The shown week may be ahead of where the cycle sits, so the wave is
    // projected that many weeks rather than repeating the current prescription.
    let projected = HCCFiveThreeOne.projectWave(
      anchorWeek: cycle.week,
      tms: cycle.tmsByLift,
      // A cycle nobody has trained yet has not spent its current week, so the
      // next calendar week is still that week — otherwise a mid-week reset of
      // the training maxes skips the new wave's 5s week. Same rule as the web.
      weekOffset: HCCFiveThreeOne.programWeekOffset(
        state.weekOffset,
        cycleHasSessions: !data.cycleSessions.isEmpty
      )
    )

    // The day being shown. Never trusted straight from state: a stored pick can
    // be a date in the other week (the strip toggles between two), so it only
    // counts when the shown week actually contains it. Today is the fallback
    // when today is in view; otherwise the first day of the week is.
    let selected =
      days.first { $0.date == state.selectedDate }
      ?? days.first { $0.date == data.todayYmd }
      ?? days.first

    HCCTrainingWeekCard(
      weekStart: weekStart,
      todayYmd: data.todayYmd,
      days: days,
      sessions: data.sessions,
      weekOffset: state.weekOffset,
      selectedDate: selected?.date,
      helper: helperText,
      onShift: { delta in
        let next = min(1, max(0, state.weekOffset + delta))
        guard next != state.weekOffset else { return }
        // Keep the same weekday across the jump, except when landing back on the
        // real calendar week, where today is the more useful default. The web
        // strip's rule, so both clients move the selection the same way.
        let carried = selected?.date ?? data.todayYmd
        state.weekOffset = next
        state.selectedDate =
          next == 0 ? data.todayYmd : HCCFiveThreeOne.addDays(carried, 7)
      },
      onSelectDay: { date in state.selectedDate = date }
    )
    .id(HCCTrainingAnchor.week.rawValue)

    // Always on screen, for whichever day is selected — it is how a day's
    // workout is changed, so it is not something to go hunting for behind a
    // second tap (Chris, 2026-09-08).
    if let day = selected {
      HCCTrainingPickerCard(
        dayKey: day.date,
        current: day,
        isEnabled: !state.isWriting,
        onPick: { choice in
          Task { await store.setHCCTrainingDayPlan(date: day.date, choice: choice) }
        }
      )
    }

    weekBody(
      data: data,
      cycle: cycle,
      days: days,
      week: projected.week,
      tms: projected.tms,
      selected: selected
    )

    // Progression belongs to the day being shown, not to the tab: on a squat +
    // bench day these are squat and bench, and on a conditioning or rest day
    // there is no lift to chart, so the block is not there at all.
    let progressionLifts = selected.map { Self.progressionLifts(day: $0, data: data) } ?? []

    ForEach(Array(progressionLifts.enumerated()), id: \.element) { offset, lift in
      HCCTrainingProgressionCard(
        lift: lift,
        trainingMaxKg: cycle.tm(lift) ?? 0,
        history: data.history(lift)
      )
      .modifier(HCCTrainingAnchorID(id: offset == 0 ? HCCTrainingAnchor.progression.rawValue : nil))
    }

    HCCTrainingButtons(specs: weekControls(cycle: cycle, data: data))
      .id(HCCTrainingAnchor.controls.rawValue)
  }

  /// The lifts whose progression belongs under the selected day: none unless it
  /// is a lifting day, and then exactly the lifts it runs, in the order it runs
  /// them — so a "Squat + Bench" day charts squat then bench, and nothing else.
  ///
  /// Logged work wins over the plan, the same rule the day's own cards use: when
  /// a strength session exists its sets name the lifts, so a day trained off-plan
  /// charts what was actually lifted rather than what was scheduled. `groupByLift`
  /// is reused for that because it already returns distinct lifts in the day's
  /// order.
  ///
  /// It replaced a fixed `[.squat, .bench, .deadlift, .press]` block that drew all
  /// four on every day, including conditioning and rest days (Chris, 2026-09-08).
  private static func progressionLifts(day: HCCResolvedDay, data: HCCTrainingData) -> [HCCLiftKey] {
    if let session = data.sessions(on: day.date).first(where: { $0.kind == .strength }) {
      let logged = groupByLift(session.sets, order: day.lifts).map(\.lift)
      if !logged.isEmpty { return logged }
    }
    // No session yet: the plan decides, and only a lifting day has lifts. Matches
    // `showsStrength` in dayCards, so the chart block and the day's card agree.
    return day.option == .strength ? day.lifts : []
  }

  private var helperText: String {
    if state.weekOffset == 0 { return "Tap a day to show it." }
    return state.nextWeekEdited
      ? "Edited. Other days still default to this week's pattern."
      : "Defaults copied from this week. Tap a day to show it."
  }

  // ── The shown week ─────────────────────────────────────────────────────────

  /// The selected day of the shown week, and only it.
  ///
  /// History, because this has moved twice. It first drew TODAY plus the next
  /// strength day still ahead — on a Sunday whose plan says rest that is a blank
  /// screen, with the week's logged sessions nowhere on the phone. So it went to
  /// every non-rest day of the week at once, which fixed the hiding but stacked
  /// several days' workouts under one tap (Chris, 2026-09-08: "it shows the
  /// workouts for multiple days"). Now it draws exactly the day the strip has
  /// selected, which is the web page's behaviour.
  ///
  /// The week is still not hidden: the strip above carries all seven days with
  /// their tags and their done marks, so any of them is one tap away. And a rest
  /// day is now reachable — it was filtered out entirely before, so a day the
  /// plan called rest could not be inspected or given a workout from here.
  @ViewBuilder
  private func weekBody(
    data: HCCTrainingData,
    cycle: HCCTrainingCycle,
    days: [HCCResolvedDay],
    week: Int,
    tms: [HCCLiftKey: Double],
    selected: HCCResolvedDay?
  ) -> some View {
    if state.weekOffset > 0 {
      HCCSectionHeader(title: "Next week")
      HCCFootnote(
        "Week \(week) — \(HCCFiveThreeOne.weekLabel(week)). Nothing here has been started; "
          + "the numbers come from that week's training maxes."
      )
    }

    if days.isEmpty {
      HCCEmptyNote("This week has not been resolved yet.").hccCard()
    } else if let day = selected {
      HCCSectionHeader(title: Self.dayHeading(day: day, todayYmd: data.todayYmd))
      dayCards(
        day: day,
        data: data,
        cycle: cycle,
        week: week,
        tms: tms,
        label: Self.dayLabel(day: day, todayYmd: data.todayYmd),
        // Only a day that has not arrived is a preview. Today and the days
        // behind it happened, so they start, log and mark like today always
        // did. Day keys are 'YYYY-MM-DD', where string order IS date order.
        isPreview: day.date > data.todayYmd
      )
    }
  }

  private static func dayHeading(day: HCCResolvedDay, todayYmd: String) -> String {
    guard day.date != todayYmd else { return "Today" }
    return "\(HCCTrainingFormat.shortDow(day.date)) \(HCCTrainingFormat.dayNumber(day.date))"
  }

  /// The pill each card carries: where this day sits relative to now. Never a
  /// claim about what happened on it — the card's own rows say that.
  private static func dayLabel(day: HCCResolvedDay, todayYmd: String) -> String {
    if day.date == todayYmd { return "Today" }
    return day.date < todayYmd ? "Earlier" : "Preview"
  }

  /// A day, drawn as one card per lift for a strength day and one card for a
  /// conditioning day.
  @ViewBuilder
  private func dayCards(
    day: HCCResolvedDay,
    data: HCCTrainingData,
    cycle: HCCTrainingCycle,
    week: Int,
    tms: [HCCLiftKey: Double],
    label: String,
    isPreview: Bool
  ) -> some View {
    let daySessions = data.sessions(on: day.date)
    let strength = daySessions.first { $0.kind == .strength }
    let conditioning = daySessions.first { $0.kind == .conditioning }
    // Logged work wins over the plan: a strength session on a conditioning day
    // still shows its lifts, and the other way round.
    let showsStrength = strength != nil || day.option == .strength
    let showsConditioning = conditioning != nil || day.option == .conditioning

    if showsStrength {
      if let session = strength {
        startedStrength(session: session, day: day, cycle: cycle, label: label)
      } else {
        previewStrength(day: day, week: week, tms: tms, label: label, canStart: !isPreview)
      }
    }

    if showsConditioning {
      HCCTrainingConditioningCard(
        title: conditioning?.title ?? day.title,
        subtitle: day.subtitle ?? "Conditioning",
        pillText: label,
        isPreview: isPreview,
        isDone: conditioning?.status == .done,
        isOptional: day.optional,
        isEnabled: !state.isWriting,
        onMark: isPreview ? nil : { markConditioning(day: day, session: conditioning) },
        // HCC: the same setup sheet Home opens, named after this day.
        onStartLive: Self.liveActivityIsAvailable && !isPreview
          ? { liveTitle = HCCTrainingLiveStart(title: conditioning?.title ?? day.title) }
          : nil
      )
      if let session = conditioning, !isPreview {
        noteCard(session: session)
      }
    }

    if !showsStrength && !showsConditioning {
      HCCEmptyNote("\(label): rest day.").hccCard()
    }
  }

  /// A strength day that has been started: the server's own stored sets, each
  /// tickable, and the AMRAP bar on the set that measures.
  @ViewBuilder
  private func startedStrength(
    session: HCCTrainingSession,
    day: HCCResolvedDay,
    cycle: HCCTrainingCycle,
    label: String
  ) -> some View {
    // The session records the week it was prescribed for; that is the week its
    // stored weights belong to, whatever the cycle has since moved to.
    let week = HCCFiveThreeOne.clampWeek(session.week ?? cycle.week)
    ForEach(Self.groupByLift(session.sets, order: day.lifts), id: \.lift) { group in
      HCCTrainingLiftCard(
        lift: group.lift,
        trainingMaxKg: cycle.tm(group.lift) ?? 0,
        week: week,
        pillText: label,
        isPreview: false,
        rows: group.sets.map {
          HCCTrainingSetTable.Row(id: $0.id, prescribed: $0.prescribed, actualReps: $0.actualReps, set: $0)
        },
        isEnabled: !state.isWriting,
        onToggle: { row in
          guard let set = row.set else { return }
          Task {
            await store.logHCCTrainingSet(
              sessionId: session.id,
              set: set,
              actualReps: set.actualReps == nil ? set.targetReps : nil
            )
          }
        },
        footer: { amrapFooter(session: session, sets: group.sets) }
      )
    }
    noteCard(session: session)
  }

  @ViewBuilder
  private func amrapFooter(session: HCCTrainingSession, sets: [HCCTrainingSet]) -> some View {
    if let amrap = sets.first(where: \.isAmrap) {
      HCCTrainingAmrapBar(
        weightKg: amrap.targetWeightKg,
        reps: state.amrapDraft(for: amrap),
        loggedReps: amrap.actualReps,
        isEnabled: !state.isWriting,
        onStep: { delta in
          state.amrapDrafts[amrap.id] = max(0, min(100, state.amrapDraft(for: amrap) + delta))
        },
        onLog: {
          let reps = state.amrapDraft(for: amrap)
          Task { await store.logHCCTrainingSet(sessionId: session.id, set: amrap, actualReps: reps) }
        }
      )
    }
  }

  /// A strength day with nothing stored yet: the prescription generated from the
  /// training maxes, and — on the day itself — the button that turns it into a
  /// session the server owns.
  @ViewBuilder
  private func previewStrength(
    day: HCCResolvedDay,
    week: Int,
    tms: [HCCLiftKey: Double],
    label: String,
    canStart: Bool
  ) -> some View {
    ForEach(day.lifts, id: \.self) { lift in
      let tm = tms[lift] ?? 0
      HCCTrainingLiftCard(
        lift: lift,
        trainingMaxKg: tm,
        week: week,
        pillText: label,
        isPreview: true,
        rows: HCCFiveThreeOne.waveSets(tmKg: tm, week: week).map {
          HCCTrainingSetTable.Row(id: "\(day.date):\(lift.rawValue):\($0.setIndex)", prescribed: $0)
        }
      )
    }
    if !day.lifts.isEmpty {
      // `canStart` was declared and never read, so every preview card — the
      // "Up next" day, and now each day next week — offered a button that
      // starts a session dated a day that has not arrived. The card says
      // Preview; it should not also say Start.
      if canStart {
        HCCButtonRow(
          primary: HCCButtonSpec(title: "Start session", isEnabled: !state.isWriting) {
            Task {
              await store.startHCCTrainingSession(
                HCCTrainingSessionCreate(
                  date: day.date,
                  kind: HCCTrainingSessionKind.strength.rawValue,
                  lifts: day.lifts.map(\.rawValue),
                  week: week
                )
              )
            }
          }
        )
      }
      HCCFootnote("Sets are generated from week \(week)'s training maxes.")
    }
  }

  private func noteCard(session: HCCTrainingSession) -> some View {
    HCCTrainingNoteField(
      placeholder: "How it felt, bar speed, anything to remember",
      text: Binding(
        get: { state.noteDraft(for: session) },
        set: { state.noteDrafts[session.id] = $0 }
      ),
      isEnabled: !state.isWriting,
      onCommit: {
        let draft = state.noteDraft(for: session).trimmingCharacters(in: .whitespacesAndNewlines)
        guard draft != (session.notes ?? "") else { return }
        Task { await store.patchHCCTrainingSession(session, notes: .some(draft.isEmpty ? nil : draft)) }
      }
    )
    .hccCard()
  }

  private func markConditioning(day: HCCResolvedDay, session: HCCTrainingSession?) {
    Task {
      if let session {
        await store.patchHCCTrainingSession(session, status: session.status == .done ? .planned : .done)
      } else {
        await store.startHCCTrainingSession(
          HCCTrainingSessionCreate(
            date: day.date,
            kind: HCCTrainingSessionKind.conditioning.rawValue,
            title: day.title,
            status: HCCTrainingSessionStatus.done.rawValue
          )
        )
      }
    }
  }

  // ── Next week ──────────────────────────────────────────────────────────────

  /// The next week is a preview, not a log: one line per day with the top set of
  /// each lift, which is the number that tells the owner how heavy the week is.
  // ── Wave controls ──────────────────────────────────────────────────────────

  /// Exactly the controls the web page offers in each state, and no others.
  /// Every step is reversible: advancing is a single tap, and without a way back
  /// a mis-tap strands the cycle a week ahead of real life.
  private func weekControls(cycle: HCCTrainingCycle, data: HCCTrainingData) -> [HCCButtonSpec] {
    var specs: [HCCButtonSpec] = []
    let busy = state.isWriting

    if cycle.week > 1 {
      specs.append(
        HCCButtonSpec(title: "Back to week \(cycle.week - 1)", isEnabled: !busy) {
          Task {
            await store.runHCCTrainingCycleAction(
              HCCTrainingCycleBody(action: "setWeek", week: cycle.week - 1)
            )
          }
        }
      )
    }

    // Offered only for a freshly-started, still-empty cycle: the server refuses
    // to delete a cycle that holds logged work, so this is never shown when it
    // could not succeed.
    if cycle.number > 1 && cycle.week == 1 && data.cycleSessions.isEmpty {
      specs.append(
        HCCButtonSpec(title: "Back to cycle \(cycle.number - 1) deload", isEnabled: !busy) {
          confirmingCycleStart = .revert(number: cycle.number)
        }
      )
    }

    if cycle.week < 4 {
      specs.append(
        HCCButtonSpec(title: "Advance to week \(cycle.week + 1)", isEnabled: !busy) {
          Task { await store.runHCCTrainingCycleAction(HCCTrainingCycleBody(action: "advanceWeek")) }
        }
      )
    }

    if cycle.week == 4 || cycle.week == 3 {
      let skipping = cycle.week != 4
      specs.append(
        HCCButtonSpec(
          title: skipping ? "Skip deload · start cycle \(cycle.number + 1)" : "Start cycle \(cycle.number + 1)",
          isEnabled: !busy
        ) {
          confirmingCycleStart = .startNext(number: cycle.number, skippingDeload: skipping, tms: cycle.tmsByLift)
        }
      )
    }

    return specs
  }

  /// The two irreversible-feeling wave moves, and what each one will do to the
  /// training maxes — spelled out before it happens, the way the web page's
  /// confirm does.
  private enum CycleStart: Identifiable {
    case startNext(number: Int, skippingDeload: Bool, tms: [HCCLiftKey: Double])
    case revert(number: Int)

    var id: String {
      switch self {
      case let .startNext(number, skipping, _): "startNext/\(number)/\(skipping)"
      case let .revert(number): "revert/\(number)"
      }
    }

    var question: String {
      switch self {
      case let .startNext(number, skipping, _):
        skipping ? "Skip the deload and start cycle \(number + 1)?" : "Start cycle \(number + 1)?"
      case let .revert(number):
        "Undo starting cycle \(number)?"
      }
    }

    var detail: String {
      switch self {
      case let .startNext(_, _, tms):
        let lines = [HCCLiftKey.squat, .bench, .deadlift, .press].compactMap { lift -> String? in
          guard let current = tms[lift] else { return nil }
          return "\(lift.label): \(HCCFiveThreeOne.formatKg(current)) → "
            + "\(HCCFiveThreeOne.formatKg(HCCFiveThreeOne.nextTm(lift, currentKg: current))) kg"
        }
        return "Training maxes become:\n" + lines.joined(separator: "\n")
      case let .revert(number):
        return "Cycle \(number) is deleted and cycle \(number - 1) reopens at its deload week."
      }
    }

    var confirmTitle: String {
      switch self {
      case .startNext: "Start"
      case .revert: "Go back"
      }
    }

    var isDestructive: Bool {
      if case .revert = self { return true }
      return false
    }

    var body: HCCTrainingCycleBody {
      switch self {
      case .startNext: HCCTrainingCycleBody(action: "startNext")
      case .revert: HCCTrainingCycleBody(action: "revertCycleStart")
      }
    }
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  /// Sets arrive ordered by lift NAME, so a "Squat + Bench" day would otherwise
  /// render bench first. The day's resolved lift order is the record of the
  /// order the workout is actually run in.
  private static func groupByLift(
    _ sets: [HCCTrainingSet],
    order: [HCCLiftKey]
  ) -> [(lift: HCCLiftKey, sets: [HCCTrainingSet])] {
    var groups: [(lift: HCCLiftKey, sets: [HCCTrainingSet])] = []
    for set in sets {
      if let index = groups.firstIndex(where: { $0.lift == set.lift }) {
        groups[index].sets.append(set)
      } else {
        groups.append((set.lift, [set]))
      }
    }
    for index in groups.indices {
      groups[index].sets.sort { $0.setIndex < $1.setIndex }
    }
    if !order.isEmpty {
      func rank(_ lift: HCCLiftKey) -> Int { order.firstIndex(of: lift) ?? order.count }
      groups.sort { rank($0.lift) < rank($1.lift) }
    }
    return groups
  }

  private func applyDebugWeekIfRequested() {
    #if DEBUG
    if ProcessInfo.processInfo.environment["HCC_DEBUG_TRAINING_WEEK"] == "next" {
      state.weekOffset = 1
    }
    if let day = ProcessInfo.processInfo.environment["HCC_DEBUG_TRAINING_PICKER"], !day.isEmpty {
      state.selectedDate = day
    }
    #endif
  }

  #if DEBUG
  /// Runs ONE write from a launch environment variable, the way the Alarm and
  /// Customize sheets' `HCC_DEBUG_SAVE` does: `simctl` cannot tap, and a write
  /// path that has never been run is not a proved write path.
  ///
  /// It calls the same store methods the buttons call — no shortcut around the
  /// optimistic/reconcile/rollback shape — so what it proves is what a tap does.
  /// It MUTATES SERVER STATE: never set it against an instance whose data you
  /// are not willing to change.
  ///
  ///   `start`                 start today's strength session
  ///   `logset`                tick the first un-logged set of today's session
  ///   `amrap:<n>`             log n reps on today's first AMRAP set
  ///   `plan:<ymd>:<key>`      set that day to that `dayOptionCatalog` key
  ///   `note:<text>`           save a note on today's session
  private func runDebugActionIfRequested() async {
    guard let raw = ProcessInfo.processInfo.environment["HCC_DEBUG_TRAINING_SAVE"], !raw.isEmpty,
          let data = state.data
    else { return }
    let parts = raw.split(separator: ":", maxSplits: 2).map(String.init)
    let today = data.sessions(on: data.todayYmd)
    let strength = today.first { $0.kind == .strength }

    switch parts.first {
    case "start":
      guard let day = data.weekPlan.first(where: { $0.date == data.todayYmd }), !day.lifts.isEmpty else { return }
      let week = HCCFiveThreeOne.projectWave(
        anchorWeek: data.cycle?.week ?? 1, tms: [:], weekOffset: 0
      ).week
      await store.startHCCTrainingSession(
        HCCTrainingSessionCreate(
          date: day.date,
          kind: HCCTrainingSessionKind.strength.rawValue,
          lifts: day.lifts.map(\.rawValue),
          week: week
        )
      )
    case "logset":
      guard let session = strength,
            let set = session.sets.first(where: { !$0.isAmrap && $0.actualReps == nil })
      else { return }
      await store.logHCCTrainingSet(sessionId: session.id, set: set, actualReps: set.targetReps)
    case "amrap":
      guard let session = strength, let set = session.sets.first(where: \.isAmrap),
            let reps = Int(parts.count > 1 ? parts[1] : "")
      else { return }
      await store.logHCCTrainingSet(sessionId: session.id, set: set, actualReps: reps)
    case "plan":
      guard parts.count == 3,
            let choice = HCCFiveThreeOne.dayOptionCatalog().first(where: { $0.key == parts[2] })
      else { return }
      await store.setHCCTrainingDayPlan(date: parts[1], choice: choice)
    case "note":
      guard let session = strength, parts.count > 1 else { return }
      await store.patchHCCTrainingSession(session, notes: .some(parts[1]))
    case "cycle":
      // `advanceWeek` / `setWeek:<n>` / `startNext` / `revertCycleStart` — the
      // wave controls, whose taps go through a confirmation the launch cannot
      // answer. This runs the same store call the confirmed button runs.
      guard parts.count > 1 else { return }
      await store.runHCCTrainingCycleAction(
        HCCTrainingCycleBody(action: parts[1], week: parts.count > 2 ? Int(parts[2]) : nil)
      )
    default:
      return
    }
    print("[hcc-training-debug] ran \(raw); lastError=\(state.lastError ?? "none")")
  }
  #endif
}

// ── Debug scroll anchors ─────────────────────────────────────────────────────

/// The scroll targets `HCC_DEBUG_TRAINING_ANCHOR` can name.
///
/// The Training tab is several screens tall and `simctl` cannot scroll; this is
/// the same trick `HCC_DEBUG_HOME_ANCHOR` uses for cloud Home, so each block can
/// be screenshotted from a launch with no UI automation. DEBUG only.
enum HCCTrainingAnchor: String, CaseIterable {
  case week
  case progression
  case controls
}

/// `.id` only when there is one to apply, so the non-anchored cards keep
/// SwiftUI's own identity rather than being handed a nil-ish constant.
private struct HCCTrainingAnchorID: ViewModifier {
  let id: String?

  func body(content: Content) -> some View {
    if let id {
      content.id(id)
    } else {
      content
    }
  }
}

extension HCCTrainingView {
  func scrollToDebugAnchorIfRequested(_ scroller: ScrollViewProxy) {
    #if DEBUG
    guard let raw = ProcessInfo.processInfo.environment["HCC_DEBUG_TRAINING_ANCHOR"],
          let anchor = HCCTrainingAnchor(rawValue: raw)
    else {
      return
    }
    // After the read lands, so the block being aimed at has its height. Several
    // times, because a debug write re-reads the payload and relays out after the
    // first jump, and a permission alert from another surface can land on top of
    // the second one.
    Task { @MainActor in
      for delay in [2, 4, 8] {
        try? await Task.sleep(for: .seconds(delay))
        scroller.scrollTo(anchor.rawValue, anchor: .top)
      }
    }
    #endif
  }
}
